---
title: "Chronic Kidney Disease Prediction"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r global, include=FALSE}
dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)  # create personal library
.libPaths(Sys.getenv("R_LIBS_USER"))  # add to the path

library(flexdashboard)
library(shiny)
 library(leaflet)
library(reshape2)
library(tidyverse)
library(shinyWidgets)
library(dygraphs)
library(magrittr); 
library(dplyr);
library(ggplot2)
library(plotly)

```

# Prediction

Inputs {.sidebar}
-----------------------------------------------------------------------

### Input: Parameters

```{r eruptions, echo=FALSE}
 address <- "https://raw.githubusercontent.com/vrose99/AdvancedDataScienceFinalProject/8acd472133dda8bf77b87648d281237419c7fced/Data/chronic_kidney_disease.csv"
raw_data <- read.csv(address)

inputPanel(
 pickerInput(
  inputId = "x_plotting",
  label = "Select X-Axis",
  choices = colnames(raw_data),
  options = list(`actions-box` = TRUE, size = 15,
    `selected-text-format` = "count > 3"), multiple = FALSE),
 pickerInput(
  inputId = "y_plotting",
  label = "Select Y-Axis",
  choices = colnames(raw_data),
  options = list(`actions-box` = TRUE, size = 15,
    `selected-text-format` = "count > 3"), multiple = FALSE),
 pickerInput(
  inputId = "coloring",
  label = "Select Colorization",
  choices = colnames(raw_data),
  options = list(`actions-box` = TRUE, size = 15,
    `selected-text-format` = "count > 3"), multiple = FALSE),
 

 checkboxGroupInput("testinput", label = h3("TestInput"), 
    choices = list("Test1" = 1, "Test2" = 2),
    selected = 1),
 
 radioButtons("radio", label = h3("TestInput2"),
    choices = list("Test1" = 1, "Test2" = 2), 
    selected = 1),
 
 checkboxInput("regression", label = h3("Regression Line"), value = TRUE)
) 
 
```


Column {.tabset}
-------------------------------------
### Data

```{r}
# data table and formatting
address <- "https://raw.githubusercontent.com/vrose99/AdvancedDataScienceFinalProject/8acd472133dda8bf77b87648d281237419c7fced/Data/chronic_kidney_disease.csv"
raw_data <- read.csv(address)

#renderPlotly({
#})


```
   
### Filtered Data Visual

```{r}
renderPlot({
  data <- raw_data[, c(input$x_plotting, input$y_plotting, input$coloring)]
    colnames(data) <- c("col1", "col2","col3")
    if (input$regression){
      ggplot(data,aes(x=col1,y=col2, color = col3)) +
         geom_point(size=2, shape=18, alpha=0.4) + 
          geom_smooth(method = 'lm',color = 'red')+
          geom_rug(alpha=0.1, size=1.5)+ 
        scale_color_gradient(low="blue", high="red")
      
    } else {
      ggplot(data,aes(x=col1,y=col2, color = col3)) +
         geom_point(size=2, shape=18, alpha=0.4) + 
          geom_rug(alpha=0.1, size=1.5)+ 
        scale_color_gradient(low="blue", high="red")
        }
})
```

### Filtered Data
```{r}

```
### Robby's Blog

### About
